site_name: Dialplan Editor - Documentation
repo_url: https://github.com/IPConnnect/dialplan-editor-docs/
theme: bootstrap4
nav:
  - Accueil: index.md
  - Mise en route: mise_en_route.md
  - Ouverture d'une configuration existante: ouverture_conf.md
  - Ajout et suppression: ajout_suppression.md
  - Modification: modification.md
plugins:
    - mkdocs-video
